<?php
/**
 * This file is part of the Reputaction project.
 *
 * @package Reputaction_ReputactionGateway
 * @author    Xavier Titi <xavier.titi@gmail.com>
 * @copyright Copyrifht (c) 2017 Reputaction
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 * 
 */


/**
 * Block for getting back Reputaction product info 
 *
 * @var $block \Reputaction\ReputactionGateway\Block\Product\ReputactionProduct
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); 

?>


